server {
    listen 80;
    server_name localhost;

    # Serve Angular app
    location / {
        root /usr/share/nginx/html/frontend; # Adjust if your output path from Angular is just /usr/share/nginx/html
        try_files $uri $uri/ /index.html;
        index index.html;
    }

    # Proxy API requests to backend
    location /SwissTech/backend/ {
        proxy_pass http://backend:80/SwissTech/backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy Image requests to backend
    location /SwissTech/Images/ {
        proxy_pass http://backend:80/SwissTech/Images/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
